---
repositories:
- name: bjw-s
  url: https://bjw-s.github.io/helm-charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: ocis
  url: https://owncloud.github.io/ocis/helm

environments:
  default:
    values:
    - ../env/prod/default.yaml
    secrets:
    - ../env/prod/secrets.yaml

  dev:
    values:
    - ../env/dev/default.yaml
    secrets:
    - ../env/dev/secrets.yaml

templates:
  default: &default
    chart: bjw-s/app-template
    values:
      - values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

---
releases:
- name: ztnet 
  namespace: ztnet 
  installed: false 
  dependencies:
    - chart: cnpg/cluster
      version: v0.1.0
  inherit:
    - template: default

- name: unifi-controller 
  namespace: unifi-controller
  installed: true 
  inherit:
    - template: default

- name: homepage 
  namespace: homepage 
  installed: true 
  inherit:
    - template: default

- name: gatus 
  namespace: gatus 
  installed: true 
  dependencies:
    - chart: cnpg/cluster
      version: v0.1.0
  inherit:
    - template: default

- name: attic 
  namespace: attic 
  installed: true 
  dependencies:
    - chart: cnpg/cluster
      version: v0.1.0
  inherit:
    - template: default

- name: changedetection 
  namespace: changedetection 
  inherit:
    - template: default

- name: unpoller 
  namespace: monitoring-ext 
  inherit:
    - template: default

- name: mktxp 
  namespace: monitoring-ext 
  inherit:
    - template: default

- name: telegraf 
  namespace: monitoring-ext 
  inherit:
    - template: default

- name: zoneit 
  namespace: zoneit 
  inherit:
    - template: default

- name: mqtt-notif 
  namespace: monitoring-ext 
  inherit:
    - template: default

- name: adguardhome 
  namespace: adguardhome 
  inherit:
    - template: default

- name: it-tools 
  namespace: it-tools 
  inherit:
    - template: default

- name: hass 
  namespace: hass 
  inherit:
    - template: default

- name: c2app-level1 
  namespace: c2app 
  inherit:
    - template: default
