apiVersion: apps/v1
kind: Deployment
metadata:
  name: monerod-stagenet
  namespace: crypto 
  labels:
    app: monerod-stagenet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monerod-stagenet
  template:
    metadata:
      labels:
        app: monerod-stagenet
    spec:
      # nodeSelector:
      #   app: dl-node
      containers:
      - name: monerod
        image: ghcr.io/sethforprivacy/simple-monerod:latest
        args:
          - "--rpc-bind-ip=0.0.0.0"
          - "--enable-dns-blocklist"
          - "--no-igd"
          - "--no-zmq"
          - "--confirm-external-bind"
          - "--out-peers=1000"
          - "--disable-rpc-ban"
          - "--stagenet"
        ports:
        - containerPort: 38081
        volumeMounts:
        - name: bitmonero-stagenet-storage
          mountPath: /home/monero/.bitmonero
          subPath: bitmonero-stagenet
      volumes:
      - name: bitmonero-stagenet-storage
        persistentVolumeClaim:
          claimName: nfs-blockchains-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: nfs-blockchains-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-blockchains
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 10.83.101.5##
    volumeAttributes:
      server: 10.83.101.5
      share: /mnt/hot/blockchains
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-blockchains-pvc
spec:
  storageClassName: nfs-blockchains
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: monerod-stagenet-service
  namespace: crypto 
  labels:
    app: monerod-stagenet
spec:
  ports:
  - port: 38081
    targetPort: 38081
  selector:
    app: monerod-stagenet
  type: LoadBalancer 
