all:
  vars:
    longhorn_device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
    ansible_python_interpreter: /usr/bin/python3

  children:
    dhcp_hosts:
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        gateway: 10.83.101.1
        netmask: 255.255.255.0
        dns_servers:
          - 10.83.100.2
      hosts:
        # k8s-controller-01:
        #   ansible_host: 10.83.101.24
        #   new_ip: 10.83.101.10
        # k8s-controller-02:
        #   ansible_host: 10.83.101.112
        #   new_ip: 10.83.101.11
        # k8s-worker-01:
        #   ansible_host: 10.83.101.117
        #   new_ip: 10.83.101.20
        # k8s-worker-02:
        #   ansible_host: 10.83.101.114
        #   new_ip: 10.83.101.21
        # k8s-worker-03:
        #    ansible_host: 10.83.101.15
        #    new_ip: 10.83.101.22
        # k8s-worker-04:
        #    ansible_host: 10.83.101.108
        #    new_ip: 10.83.101.23
        # k8s-worker-05.int.mazenet.org:
        #    ansible_host: 10.83.101.106
        #    new_ip: 10.83.101.24

    k8s:
      hosts:
        k8s-controller-01.int.mazenet.org:
        k8s-controller-02.int.mazenet.org:
        k8s-worker-01.int.mazenet.org:
          cache_device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2
        k8s-worker-02.int.mazenet.org:
          longhorn_device: /dev/vdb
        k8s-worker-03.int.mazenet.org:
        k8s-worker-04.int.mazenet.org:
        k8s-worker-05.int.mazenet.org:

    k3s_cluster:
      hosts:
        k8s-worker-01.int.mazenet.org:
          k3s_etcd_datastore: true
          k3s_control_node: true
        k8s-worker-02.int.mazenet.org:
          k3s_etcd_datastore: true
          k3s_control_node: true
        # k8s-worker-03.int.mazenet.org:
        #   k3s_etcd_datastore: true
        #   k3s_control_node: true
        #   is_bare_metal: true
        k8s-worker-04.int.mazenet.org:
          k3s_etcd_datastore: true
          k3s_control_node: true
          is_bare_metal: true
        k8s-worker-05.int.mazenet.org:
          # k3s_etcd_datastore: true
          # k3s_control_node: true
          is_bare_metal: true

    mikrotik:
      vars:
        ansible_ssh_common_args: "-J bastion"
        ansible_user: "admin"
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: community.routeros.routeros
      hosts:
        # hm01-rt01:
        #   ansible_host: 10.83.10.1
        hm01-sw01:
          ansible_host: 10.83.10.251
        hm01-sw02:
          ansible_host: 10.83.10.252
