---
- name: Check k3s and Kubernetes versions
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Get k3s version
      command: k3s --version
      register: k3s_version
      ignore_errors: true

    - name: Display k3s version
      debug:
        var: k3s_version.stdout

    - name: Get Kubernetes version
      command: kubectl version
      register: k8s_version
      ignore_errors: true

    - name: Display Kubernetes version
      debug:
        var: k8s_version.stdout
